/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu;

import hu.controller.ARateController;
import hu.controller.BRateController;
import hu.entity.A;
import hu.entity.B;
import hu.repository.ARepository;
import hu.repository.BRepository;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omur.alcin
 */
public class Karar extends javax.swing.JFrame {

    private ARateController aRateController;
    private BRateController bRateController;
    private ARepository aRepository ;
    private BRepository bRepository ;
    public static A a ;
    public static B b ;

    /**
     * Creates new form Karar
     */
    public Karar() {
        initComponents();
        a =  new A();
        b =  new B();
        aRateController = new ARateController();
        bRateController = new BRateController();
        aRepository = new ARepository();
        bRepository = new BRepository();
                a = aRepository.find(1);   
                b = bRepository.find(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_secenekler = new javax.swing.ButtonGroup();
        rdbtn_sag = new javax.swing.JRadioButton();
        rdbtn_sol = new javax.swing.JRadioButton();
        btn_sec = new javax.swing.JButton();
        txt_sag = new javax.swing.JTextField();
        txt_sol = new javax.swing.JTextField();
        btn_sifirla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btngrp_secenekler.add(rdbtn_sag);
        rdbtn_sag.setText("Sag");

        btngrp_secenekler.add(rdbtn_sol);
        rdbtn_sol.setText("Sol");

        btn_sec.setText("Seç");
        btn_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secActionPerformed(evt);
            }
        });

        btn_sifirla.setText("Sıfırla");
        btn_sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sifirlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtn_sag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_sag, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtn_sol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_sec)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_sifirla)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_sifirla)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtn_sag)
                    .addComponent(txt_sag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btn_sec)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtn_sol)
                    .addComponent(txt_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void solSecildi(){
    try {
                
                int rate_sol;
                if (txt_sol.getText().equals("")) {
                    rate_sol = 0;
                } else {
                    rate_sol = Integer.parseInt(txt_sol.getText());
                }
                

                bRateController.bRateIncreaser(rate_sol);
                
              
                
                JOptionPane.showMessageDialog(rootPane, "A Fear : " + a.getFear() + " - A Goal : " + a.getGoal()+"\n"
                        +"B Fear : " + b.getFear() + " - B Goal : " + b.getGoal());
                 
            } catch (Exception e) {
                Logger.getLogger(Karar.class.getName()).log(Level.SEVERE, null, e);
            }
    }
    public void sagSecildi(){
                try {
              
                int rate;
                if (txt_sag.getText().equals("")) {
                    rate = 0;
                } else {
                    rate = Integer.parseInt(txt_sag.getText());
                }
  

                aRateController.aRateIncreaser(rate);
                
////                a.setFear(aRepository.find(1).getFear()); 
////                a.setGoal(aRepository.find(1).getGoal()); 
////                b.setFear(bRepository.find(1).getFear());
////                b.setGoal(bRepository.find(1).getGoal());

                JOptionPane.showMessageDialog(rootPane, "A Fear : " + a.getFear() + " - A Goal : " + a.getGoal()+"\n"
                        +"B Fear : " + b.getFear() + " - B Goal : " + b.getGoal());
               
            } catch (Exception ex) {
                Logger.getLogger(Karar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    private void btn_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secActionPerformed
        // TODO add your handling code here:
        if (rdbtn_sag.isSelected()) {
                sagSecildi();
        } else if(rdbtn_sol.isSelected()) {
                solSecildi();
        }
    }//GEN-LAST:event_btn_secActionPerformed

    private void btn_sifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sifirlaActionPerformed
        // TODO add your handling code here:
         A a = new A();
         B b = new B();
          ARepository arep = new ARepository();
          a.setFear(arep.find(1).getFear());
          a.setGoal(arep.find(1).getGoal());
          a.setFear(50);
          a.setGoal(50);
          arep.save(a);
          
          BRepository brep = new BRepository();
          b.setFear(brep.find(1).getFear());
          b.setGoal(brep.find(1).getGoal());
          b.setFear(50);
          b.setGoal(50);
          brep.save(b);
 
          JOptionPane.showMessageDialog(rootPane, "A Fear : " + a.getFear() + " - A Goal : " + a.getGoal()+"\n"
                        +"B Fear : " + b.getFear() + " - B Goal : " + b.getGoal());
               
        
    }//GEN-LAST:event_btn_sifirlaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sec;
    private javax.swing.JButton btn_sifirla;
    private javax.swing.ButtonGroup btngrp_secenekler;
    private javax.swing.JRadioButton rdbtn_sag;
    private javax.swing.JRadioButton rdbtn_sol;
    private javax.swing.JTextField txt_sag;
    private javax.swing.JTextField txt_sol;
    // End of variables declaration//GEN-END:variables
}
